const Strings = {
  login: 'Login',
  email: 'Email',
  password: 'Password',
  signUpLabel: "Don't have an account ? ",
  signUpLink: 'Create One',
  loginBtn: 'Login',
  homeMessage: 'Welcome!',
  logoutBtn: 'Logout',
  errorAlertTitle: 'Oops!',
  alertBtn: 'Ok',
  inDevelopmentAlert: 'this screen is currently in development',
  signUp: 'SignUp',
  userName: 'UserName',
  confirmPassword: 'ConfirmPassword',
  createAccount: 'Create Account',
  forgotPassword: 'Forgot Password',
  resetPassword: 'Reset Password',
  signedUpSuccess: 'Sign Up successfully',
  emailAlreadyPresent: 'Email already in use !',
  emailNotFormatted: 'The email address is badly formatted',
  internalError: 'Internal Error!',
  HomePageHeaderTitle: 'Contacts',
  userNotFound: 'There is no user record corresponding to this identifier',
  emailSentSuccess: 'Email Sent Successfully',
  navigateToLogin: 'Go To Login Page',
  mailSentSuccess: 'Mail for Reset Password is sent successfully',
  noContacts: 'No Contacts.',
  logoutAlertMessage: 'Are you sure you want to logout ?',
  logoutAlertTitle: 'Logout',
  yesBtn: 'Yes',
  noBtn: 'No',
  navigateToShowContacts: 'Go to Contacts Page',
  addContacts: 'Add Contacts',
  createDate: 'Created Date: ',
  editContact: 'Edit Contact',
  deleteContact: 'Delete Contact',
  updateDate: 'Updated Date: ',
  editSuccessMessage: 'Contact Edited Successfully',
  deleteSuccessMessage: 'Contact Deleted Successfully',
  surityMessage: 'Are You Sure?',
  editSurityMessage: 'Contact will be Updated!',
  deleteSurityMessage: 'Contact will be Deleted!',
};

export default Strings;
